### ISSUE TITLE
Отсутствие примеров работы с SDK на стороне сервера

### ISSUE THREAD

**Issue by MSITETOP** [bitrix24/b24jssdk#1]
Добрый день!

Я заметил, что в документации к JS SDK Bitrix24 отсутствуют примеры работы с SDK на стороне сервера. Все примеры, которые присутствуют в документации, показывают работу с вебхуками, но они выполняются с фронтенда, что, как вы сами указываете, не является рекомендуемой практикой.

![photo_2024-11-20_22-03-47 (2)](https://github.com/user-attachments/assets/acf3d1f5-1830-4a91-b277-8b4d85098e69)
![screenshot-localhost_3000-2024_11_20-22_01_46](https://github.com/user-attachments/assets/3eae1209-fbb4-4fb3-842f-b71a35992172)

Я хотел бы использовать SDK для работы с серверной логикой, но столкнулся с рядом ошибок, которые не смог преодолеть. В связи с этим у меня есть несколько вопросов:

1. Есть ли возможности использовать SDK для работы с REST API из бэкенда?
2. Если эта история все-таки подходит для бэка, не планируется ли добавить кроме вебхуков и механизмы авторизации для приложений?
3. Если SDK предназначен только для фронтенда, то зачем там вебхуки (зашитый статик токен доступа)?
4. Почему в документации отсутствует информация и примеры работы с вебхуками на серверной стороне?
5. Почему нет возможности работы с REST API из встроек, используя авторизацию текущего пользователя? 

Я был бы очень признателен, если бы вы могли предоставить примеры работы с SDK на серверной стороне или пояснить, как правильно использовать вебхуки и REST API в данном контексте.

Спасибо за внимание к моему запросу!

**Comment by IgorShevchik** [comment]
Hello

2-3 days and we'll roll out examples

**Comment by IgorShevchik** [comment]
Hi
> Я хотел бы использовать SDK для работы с серверной логикой, но столкнулся с рядом ошибок, которые не смог преодолеть.

The version has been updated to 0.1.6. Minor issues have been fixed. If there are any problems, please report them in a new issue.

> 1. Есть ли возможности использовать SDK для работы с REST API из бэкенда?

Yes, there is. Here is an [example](https://github.com/bitrix24/b24sdk-examples/tree/main/js/05-node-hook) and an [article](https://bitrix24.github.io/b24jssdk/guide/example-hook-node-work.html)

> 2. Если эта история все-таки подходит для бэка, не планируется ли добавить кроме вебхуков и механизмы авторизации для приложений?

Yes, we are planning to. There will be a B24OAuth class. Your code will handle token storage. This class will handle communication with Bitrix24.

The task is not a priority and is expected to be completed around spring 2025.

> 3. Если SDK предназначен только для фронтенда, то зачем там вебхуки (зашитый статик токен доступа)?

The SDK is for everything. Fearless adventurers use hooks on the front-end for their needs and keep the code hidden.

> 4. Почему в документации отсутствует информация и примеры работы с вебхуками на серверной стороне?

It's quite simple: it hasn't been done yet. It was supposed to be released around this time. You asked the question a bit earlier.

Here is an [example](https://github.com/bitrix24/b24sdk-examples/tree/main/js/05-node-hook) and an [article](https://bitrix24.github.io/b24jssdk/guide/example-hook-node-work.html)

> 5. Почему нет возможности работы с REST API из встроек, используя авторизацию текущего пользователя?

The question seems a bit out of context.

Look, embedding code on the client side provides all access relative to the current user. That's why everything works on the front-end side.

It's hard to say what's happening on your back-end. You might be storing something from the moment the application is installed, mishandling POST requests from the embedding, or breaking the logic in some other way. We would need to look at your specific example (this would be a different issue if you are using the current module).

I hope this answers your questions.
